# This is the configuration file for deploying the Node.js application to Google App Engine.

# The runtime specifies the Node.js version to use. Node.js 24 is the latest LTS version as of this writing.
runtime: nodejs24

# The instance class defines the amount of memory and CPU available to your application.
# F1 is the smallest instance class, suitable for low-traffic applications. You can adjust this based on your app's performance needs and budget.
instance_class: F1

# The automatic_scaling section configures how the application scales based on traffic. You can adjust the min_instances and max_instances values based on your expected traffic and budget. The target_cpu_utilization and max_concurrent_requests settings help optimize performance and resource usage.
automatic_scaling:
  min_instances: 0 # Set to 0 to allow the app to scale down to zero when not in use
  max_instances: 5 # Adjust this based on your expected traffic and budget
  target_cpu_utilization: 0.65 # Adjust this based on your app's performance characteristics
  max_concurrent_requests: 10 

# The beta_settings section is used to configure settings that are in beta, such as connecting to a Cloud SQL instance. The cloud_sql_instances field specifies the connection name of the Cloud SQL instance that your application will connect to.
beta_settings:
  cloud_sql_instances: 'lyrical-amulet-495920-u8:us-east4:postgresql'

# The env_variables section is used to define environment variables that your application can access. These variables can include sensitive information such as API keys or database connection strings. In this case, we are defining the NODE_ENV variable to indicate that the application is running in production mode, and we are also specifying the project ID and instance connection name for the Cloud SQL instance.
env_variables:
  NODE_ENV: 'production'
  SECRETS_PROJECT_ID: 'lyrical-amulet-495920-u8' # add the project ID hosting the secrets here
  INSTANCE_CONNECTION_NAME: 'lyrical-amulet-495920-u8:us-east4:postgresql'
